[package]
name = "ttt-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = { version = "4.1", features = ["rustls"] }
actix = "0.13"
dotenv = "0.15"
log = "0.4"
env_logger = "0.9"
serde = "1.0"
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
lazy_static = "1.4"
uuid = { version = "1.1", features = ["serde", "v4"] }
argonautica = "0.2"
lettre = "0.10"
lettre_email = "0.9"
actix-session = { version = "0.7", features = ["redis-rs-session", "redis-rs-tls-session"] }
actix-web-actors = "4.1"
derive_more = "0.99"
base64 = "0.13"
redis = "0.21"
rustls = "0.20"
rustls-pemfile = "1.0"
futures = "0.3"

[dependencies.ttt-db]
path = "./ttt-db"

[dependencies.ttt-matchmaking]
path = "./ttt-matchmaking"

[dependencies.ttt-game-server]
path = "./ttt-game-server"