FROM rust:1.65-alpine3.16
WORKDIR /app
RUN --mount=type=cache,target=$CARGO_HOME/registry
ENV CARGO_TARGET_DIR=target/docker
RUN apk add --no-cache musl-dev
RUN cargo install cargo-watch systemfd

ENTRYPOINT ["cargo", "watch", "-x", "run"]